# Step 1: Create a new file in your repository at .github/workflows/hello_world.yml

name: Hello World Workflow

on:
 workflow_dispatch:
jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name:  Run Python script
      run: |
        python ./Addition/add.py -Number1 5 -Number2 10
    - name:  Run Python script
      run: |
        python ./Addition/addition.py -Number1 5 -Number2 10 -Number3 15
    - name:  Run Python script
      run: |
        python ./Multiplication/multiply.py -Number1 5 -Number2 10
    - name:  Run Python script
      run: |     
        python ./Multiplication/multiply3.py -Number1 2 -Number2 3 -Number3 4
      
    
