name: Conditional Script Execution Workflow

on:
  workflow_dispatch:
    inputs:
      comp:
        description: 'Component to run'
        required: true
        default: 'comp1'
        type: choice
        options:
          - comp1
          - comp2
          - comp4

jobs:
  execute-scripts-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

 
    - name: Read and execute scripts
      run: |
        comp=${{ github.event.inputs.comp }}
        echo "Component selected: $comp"
        while IFS= read -r line; do
          script=$(echo $line | awk '{print $1}')
          if [ "$comp" == "comp1" ]; then
            if [[ $script == Addition/* || $script == Subtraction/* ]]; then
              echo "Running script: $line"
              python $line
            fi
          elif [ "$comp" == "comp2" ]; then
            if [[ $script == Addition/* || $script == Multiplication/* ]]; then
              echo "Running script: $line"
              python $line
            fi
          elif [ "$comp" == "comp4" ]; then
            echo "Running script: $line"
            python $line
          else
            echo "Invalid component specified"
            exit 1
          fi
        done < scripts_to_run.txt
